service: bgcscraper

frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
      Resource: 
        - "arn:aws:dynamodb:us-east-1:585247497817:table/products"

functions:
  scraper:
    handler: dist/handler.handlerScrapperBd

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S 
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
