service: bgcscraper

frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: 
        - "arn:aws:dynamodb:as-east-1:585247497817:table/products"

functions:
  scraper:
    handler: dist/handler.handlerScrapperBd
    events:
      - http:
          path: /products/scrapper
          method: GET

  
  getItems:
    handler: dist/products/handlerGet.getItems
    events:
      - http:
          path: /items
          method: GET

  getAllCategory:
    handler: dist/categories/category.getAll
    events:
      - http:
          path: /category
          method: GET


resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S 
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
